services:
  gateway:
    build: .
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    container_name: gateway
    ports:
      - "8090:8090"

networks:
  app-network:
    driver: bridge

